name: catbreeds
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  dio: ^5.4.3+1
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  image: assets/images/splash.jpeg
  android_gravity: fill
  color: "#FFFFFF"
  android: true
  ios: true
  fullscreen: true
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: JoseFin Sans
      fonts:
        - asset: assets/fonts/JosefinSans/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans/JosefinSans-SemiBold.ttf
          weight: 600
